version: "3.8"

services:
  chat-app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    command: python main.py
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
